package mira

// Base is the basic reddit base URL, authed is the base URL for use once authenticated

const (
	RedditBase  = "https://www.reddit.com/"
	RedditOauth = "https://oauth.reddit.com"

	// All of them are requested via oauth
	RedditApiMe          = RedditOauth + "/api/v1/me"
	RedditApiMeBlocked   = RedditOauth + "/api/v1/me/blocked"
	RedditApiMeFriends   = RedditOauth + "/api/v1/me/friends"
	RedditApiMeKarma     = RedditOauth + "/api/v1/me/karma"
	RedditApiMePrefs     = RedditOauth + "/api/v1/me/prefs"
	RedditApiMeTrophies  = RedditOauth + "/api/v1/me/trophies"
	RedditPrefsBlocked   = RedditOauth + "/prefs/blocked"
	RedditPrefsFriends   = RedditOauth + "/prefs/friends"
	RedditPrefsMessaging = RedditOauth + "/prefs/messaging"
	RedditPrefsTrusted   = RedditOauth + "/prefs/trusted"
	RedditPrefsWhere     = RedditOauth + "/prefs/where"

	// "/api/needs_captcha"

	// "/api/v1/collections/add_post_to_collection"
	// "/api/v1/collections/collection"
	// "/api/v1/collections/create_collection"
	// "/api/v1/collections/delete_collection"
	// "/api/v1/collections/follow_collection"
	// "/api/v1/collections/remove_post_in_collection"
	// "/api/v1/collections/reorder_collection"
	// "/api/v1/collections/subreddit_collections"
	// "/api/v1/collections/update_collection_description"
	// "/api/v1/collections/update_collection_title"

	// "/api/v1/subreddit/emoji.json"
	// "/api/v1/subreddit/emoji/emoji_name"
	// "/api/v1/subreddit/emoji_asset_upload_s3.json"
	// "/api/v1/subreddit/emoji_custom_size"
	// "/api/v1/subreddit/emojis/all"

	// "/api/clearflairtemplates"
	// "/api/deleteflair"
	// "/api/deleteflairtemplate"
	// "/api/flair"
	// "/api/flair_template_order"
	// "/api/flairconfig"
	// "/api/flaircsv"
	// "/api/flairlist"
	// "/api/flairselector"
	// "/api/flairtemplate"
	// "/api/flairtemplate_v2"
	// "/api/link_flair"
	// "/api/link_flair_v2"
	// "/api/selectflair"
	// "/api/setflairenabled"
	// "/api/user_flair"
	// "/api/user_flair_v2"

	// "/api/v1/gold/gild/fullname"
	// "/api/v1/gold/give/username"

	// "/api/comment"
	// "/api/del"
	// "/api/editusertext"
	// "/api/event_post_time"
	// "/api/follow_post"
	// "/api/hide"
	// "/api/info"
	// "/api/lock"
	// "/api/marknsfw"
	// "/api/morechildren"
	// "/api/report"
	// "/api/save"
	// "/api/saved_categories"
	// "/api/sendreplies"
	// "/api/set_contest_mode"
	// "/api/set_subreddit_sticky"
	// "/api/set_suggested_sort"
	// "/api/spoiler"
	// "/api/store_visits"
	// "/api/submit"
	// "/api/unhide"
	// "/api/unlock"
	// "/api/unmarknsfw"
	// "/api/unsave"
	// "/api/unspoiler"
	// "/api/vote"

	// "/api/trending_subreddits"
	// "/best"
	// "/by_id/names"
	// "/comments/article"
	// "/controversial"
	// "/duplicates/article"
	// "/hot"
	// "/new"
	// "/random"
	// "/rising"
	// "/top"
	// "/sort"

	// "/api/live/by_id/names"
	// "/api/live/create"
	// "/api/live/happening_now"
	// "/api/live/thread/accept_contributor_invite"
	// "/api/live/thread/close_thread"
	// "/api/live/thread/delete_update"
	// "/api/live/thread/edit"
	// "/api/live/thread/hide_discussion"
	// "/api/live/thread/invite_contributor"
	// "/api/live/thread/leave_contributor"
	// "/api/live/thread/report"
	// "/api/live/thread/rm_contributor"
	// "/api/live/thread/rm_contributor_invite"
	// "/api/live/thread/set_contributor_permissions"
	// "/api/live/thread/strike_update"
	// "/api/live/thread/unhide_discussion"
	// "/api/live/thread/update"
	// "/live/thread"
	// "/live/thread/about"
	// "/live/thread/contributors"
	// "/live/thread/discussions"
	// "/live/thread/updates/update_id"

	// "/api/block"
	// "/api/collapse_message"
	// "/api/compose"
	// "/api/del_msg"
	// "/api/read_all_messages"
	// "/api/read_message"
	// "/api/unblock_subreddit"
	// "/api/uncollapse_message"
	// "/api/unread_message"
	// "/message/inbox"
	// "/message/sent"
	// "/message/unread"
	// "/message/where"

	// "/api/saved_media_text"
	// "/api/v1/scopes"
	// "moderation"
	// "/about/edited"
	// "/about/log"
	// "/about/modqueue"
	// "/about/reports"
	// "/about/spam"
	// "/about/unmoderated"
	// "/about/location"
	// "/api/accept_moderator_invite"
	// "/api/approve"
	// "/api/distinguish"
	// "/api/ignore_reports"
	// "/api/leavecontributor"
	// "/api/leavemoderator"
	// "/api/mute_message_author"
	// "/api/remove"
	// "/api/unignore_reports"
	// "/api/unmute_message_author"
	// "/stylesheet"

	// "/api/mod/bulk_read"
	// "/api/mod/conversations"
	// "/api/mod/conversations/:conversation_id"
	// "/api/mod/conversations/:conversation_id/archive"
	// "/api/mod/conversations/:conversation_id/highlight"
	// "/api/mod/conversations/:conversation_id/mute"
	// "/api/mod/conversations/:conversation_id/unarchive"
	// "/api/mod/conversations/:conversation_id/unmute"
	// "/api/mod/conversations/:conversation_id/user"
	// "/api/mod/conversations/read"
	// "/api/mod/conversations/subreddits"
	// "/api/mod/conversations/unread"
	// "/api/mod/conversations/unread/count"

	// "/api/filter/filterpath"
	// "/api/filter/filterpath/r/srname"
	// "/api/multi/copy"
	// "/api/multi/mine"
	// "/api/multi/rename"
	// "/api/multi/user/username"
	// "/api/multi/multipath"
	// "/api/multi/multipath/description"
	// "/api/multi/multipath/r/srname"

	// "/search"

	// "/about/banned"
	// "/about/contributors"
	// "/about/moderators"
	// "/about/muted"
	// "/about/wikibanned"
	// "/about/wikicontributors"
	// "/about/where"
	// "/api/delete_sr_banner"
	// "/api/delete_sr_header"
	// "/api/delete_sr_icon"
	// "/api/delete_sr_img"
	// "/api/recommend/sr/srnames"
	// "/api/search_reddit_names"
	// "/api/search_subreddits"
	// "/api/site_admin"
	// "/api/submit_text"
	// "/api/subreddit_autocomplete"
	// "/api/subreddit_autocomplete_v2"
	// "/api/subreddit_stylesheet"
	// "/api/subscribe"
	// "/api/upload_sr_img"
	// "/profiles/search"
	// "/r/subreddit/about"
	// "/r/subreddit/about/edit"
	// "/r/subreddit/about/rules"
	// "/r/subreddit/about/traffic"
	// "/sidebar"
	// "/sticky"
	// "/subreddits/default"
	// "/subreddits/gold"
	// "/subreddits/mine/contributor"
	// "/subreddits/mine/moderator"
	// "/subreddits/mine/streams"
	// "/subreddits/mine/subscriber"
	// "/subreddits/mine/where"
	// "/subreddits/new"
	// "/subreddits/popular"
	// "/subreddits/search"
	// "/subreddits/where"
	// "/users/new"
	// "/users/popular"
	// "/users/where"

	// "/api/block_user"
	// "/api/friend"
	// "/api/report_user"
	// "/api/setpermissions"
	// "/api/unfriend"
	// "/api/user_data_by_account_ids"
	// "/api/username_available"
	// "/api/v1/me/friends/username"
	// "/api/v1/user/username/trophies"
	// "/user/username/about"
	// "/user/username/comments"
	// "/user/username/downvoted"
	// "/user/username/gilded"
	// "/user/username/hidden"
	// "/user/username/overview"
	// "/user/username/saved"
	// "/user/username/submitted"
	// "/user/username/upvoted"
	// "/user/username/where"

	// "/api/widget"
	// "/api/widget/widget_id"
	// "/api/widget_image_upload_s3"
	// "/api/widget_order/section"
	// "/api/widgets"

	// "/api/wiki/alloweditor/add"
	// "/api/wiki/alloweditor/del"
	// "/api/wiki/alloweditor/act"
	// "/api/wiki/edit"
	// "/api/wiki/hide"
	// "/api/wiki/revert"
	// "/wiki/discussions/page"
	// "/wiki/pages"
	// "/wiki/revisions"
	// "/wiki/revisions/page"
	// "/wiki/settings/page"
	// "/wiki/page"

	subredditExampleJson = `{"kind": "t5","data": {"user_flair_background_color": null,"submit_text_html": null,"restrict_posting": true,"user_is_banned": false,"free_form_reports": true,"wiki_enabled": null,"user_is_muted": false,"user_can_flair_in_sr": null,"display_name": "MemeInvestor_bot","header_img": null,"title": "MemeInvestor_bot","icon_size": [256,256],"primary_color": "","active_user_count": 2,"icon_img": "https:\/\/b.thumbs.redditmedia.com\/bz7E9y0Ca7UZS7QBCesV2aRavkZ9ZydYBYdsqRzdY1A.png","display_name_prefixed": "r\/MemeInvestor_bot","accounts_active": 2,"public_traffic": false,"subscribers": 1339,"user_flair_richtext": [],"videostream_links_count": 0,"name": "t5_m0je4","quarantine": false,"hide_ads": false,"emojis_enabled": false,"advertiser_category": "","public_description": "This subreddit is for questions, reports, or suggestions regarding \/u\/MemeInvestor_Bot. \n\nFor quick information see https:\/\/memes.market","comment_score_hide_mins": 0,"user_has_favorited": false,"user_flair_template_id": null,"community_icon": "","banner_background_image": "https:\/\/styles.redditmedia.com\/t5_m0je4\/styles\/bannerBackgroundImage_nin8va4paya11.png","original_content_tag_enabled": false,"submit_text": "","description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;h6&gt;This is the official subreddit for the bot, &lt;a href=\"\/u\/MemeInvestor_bot\"&gt;\/u\/MemeInvestor_bot&lt;\/a&gt;&lt;\/h6&gt;\n\n&lt;hr\/&gt;\n\n&lt;p&gt;Here you&amp;#39;re encouraged to &lt;strong&gt;report bugs, ask questions, and submit suggestions&lt;\/strong&gt; regarding the bot. This subreddit is frequently viewed by the developers and, whether or not you receive a reply, it&amp;#39;s very likely that your submission has been viewed and noted by someone on the team.&lt;\/p&gt;\n\n&lt;hr\/&gt;\n\n&lt;h5&gt;Rules:&lt;\/h5&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;p&gt;This is a no-meme subreddit. Only serious suggestions, reports, or questions allowed.&lt;\/p&gt;&lt;\/li&gt;\n&lt;li&gt;&lt;p&gt;All content must be regarding the bot. Keep it on-topic please.&lt;\/p&gt;&lt;\/li&gt;\n&lt;li&gt;&lt;p&gt;Be respectful. We&amp;#39;re all nice people here.&lt;\/p&gt;&lt;\/li&gt;\n&lt;\/ol&gt;\n\n&lt;hr\/&gt;\n\n&lt;p&gt;&amp;nbsp;&lt;\/p&gt;\n\n&lt;h4&gt;&lt;sup&gt;Please don&amp;#39;t send a message before first submitting your post on the subreddit.&lt;\/sup&gt;&lt;\/h4&gt;\n\n&lt;h6&gt;&lt;strong&gt;&lt;a href=\"https:\/\/www.reddit.com\/message\/compose?to=%2Fr%2FMemeInvestor_Bot\"&gt;Message us anyway.&lt;\/a&gt;&lt;\/strong&gt;&lt;\/h6&gt;\n&lt;\/div&gt;&lt;!-- SC_ON --&gt;","spoilers_enabled": true,"header_title": null,"header_size": null,"user_flair_position": "right","all_original_content": false,"has_menu_widget": false,"is_enrolled_in_new_modmail": null,"key_color": "#545452","can_assign_user_flair": false,"created": 1532043541.0,"wls": null,"show_media_preview": true,"submission_type": "any","user_is_subscriber": false,"disable_contributor_requests": false,"allow_videogifs": true,"user_flair_type": "text","collapse_deleted_comments": false,"emojis_custom_size": null,"public_description_html": "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;This subreddit is for questions, reports, or suggestions regarding &lt;a href=\"\/u\/MemeInvestor_Bot\"&gt;\/u\/MemeInvestor_Bot&lt;\/a&gt;. &lt;\/p&gt;\n\n&lt;p&gt;For quick information see &lt;a href=\"https:\/\/memes.market\"&gt;https:\/\/memes.market&lt;\/a&gt;&lt;\/p&gt;\n&lt;\/div&gt;&lt;!-- SC_ON --&gt;","allow_videos": true,"notification_level": null,"can_assign_link_flair": true,"accounts_active_is_fuzzed": false,"submit_text_label": null,"link_flair_position": "right","user_sr_flair_enabled": true,"user_flair_enabled_in_sr": true,"allow_discovery": true,"user_sr_theme_enabled": true,"link_flair_enabled": true,"subreddit_type": "public","suggested_comment_sort": null,"banner_img": "https:\/\/b.thumbs.redditmedia.com\/Wqk7-zU-_lHm1-Oqd-Pg6fnShz2tKwNiFkV9Y23mwCM.png","user_flair_text": null,"banner_background_color": "","show_media": true,"id": "m0je4","user_is_moderator": false,"over18": false,"description": "######This is the official subreddit for the bot, \/u\/MemeInvestor_bot\n\n***\n\nHere you're encouraged to **report bugs, ask questions, and submit suggestions** regarding the bot. This subreddit is frequently viewed by the developers and, whether or not you receive a reply, it's very likely that your submission has been viewed and noted by someone on the team.\n\n***\n\n#####Rules:\n1. This is a no-meme subreddit. Only serious suggestions, reports, or questions allowed.\n\n2.  All content must be regarding the bot. Keep it on-topic please.\n\n3. Be respectful. We're all nice people here.\n\n***\n\n&amp;nbsp;\n\n####^(Please don't send a message before first submitting your post on the subreddit.)\n\n######**[Message us anyway.](https:\/\/www.reddit.com\/message\/compose?to=%2Fr%2FMemeInvestor_Bot)**","submit_link_label": null,"user_flair_text_color": null,"restrict_commenting": false,"user_flair_css_class": null,"allow_images": true,"lang": "en","whitelist_status": null,"url": "\/r\/MemeInvestor_bot\/","created_utc": 1532014741.0,"banner_size": [654,196],"mobile_banner_image": "","user_is_contributor": false}}`
	redditorExampleJson  = `{"kind": "t2", "data": {"is_employee": false, "icon_img": "https://a.thumbs.redditmedia.com/7kijh7qQbAFMWNG0y5k1Jg8FARuO_tsYshB13cq9Ah4.png", "pref_show_snoovatar": false, "name": "Thecsw", "is_friend": false, "created": 1427243659.0, "has_subscribed": true, "hide_from_robots": false, "created_utc": 1427214859.0, "link_karma": 4338, "comment_karma": 1972, "is_gold": false, "is_mod": true, "verified": true, "subreddit": {"default_set": true, "user_is_contributor": false, "banner_img": "https://b.thumbs.redditmedia.com/HmQ2FMp9qK8GK_-j-wRTQKaScG6hOcNz0cSYa2fopxY.png", "disable_contributor_requests": false, "user_is_banned": false, "free_form_reports": true, "community_icon": "", "show_media": true, "icon_color": "", "user_is_muted": false, "display_name": "u_Thecsw", "header_img": null, "title": "thecsw", "over_18": false, "icon_size": [256, 256], "primary_color": "", "icon_img": "https://a.thumbs.redditmedia.com/7kijh7qQbAFMWNG0y5k1Jg8FARuO_tsYshB13cq9Ah4.png", "description": "", "header_size": null, "restrict_posting": true, "restrict_commenting": false, "subscribers": 0, "is_default_icon": false, "link_flair_position": "", "display_name_prefixed": "u/Thecsw", "key_color": "", "name": "t5_3p2jb", "is_default_banner": false, "url": "/user/Thecsw/", "banner_size": [1280, 384], "user_is_moderator": false, "public_description": "GIT d++ s+:- a--- C++ UL P! L++ E W+++ N+++ o K- w++ O--- M- V PS PE+ Y+ PGP++ t 5- X++ R !tv b+++ DI+ D+ \nG++ e++ h r y", "link_flair_enabled": false, "subreddit_type": "user", "user_is_subscriber": false}, "has_verified_email": true, "id": "mglj6"}}`

	meExampleJson = `{"is_employee": false, "seen_layout_switch": false, "has_visited_new_profile": true, "pref_no_profanity": true, "has_external_account": false, "pref_geopopular": "", "seen_redesign_modal": false, "pref_show_trending": true, "subreddit": {"default_set": true, "user_is_contributor": false, "banner_img": "", "disable_contributor_requests": false, "user_is_banned": false, "free_form_reports": true, "community_icon": "", "show_media": true, "icon_color": "#7E53C1", "user_is_muted": false, "display_name": "u_HiveWriting_bot", "header_img": null, "title": "", "over_18": false, "icon_size": [256, 256], "primary_color": "", "icon_img": "https://www.redditstatic.com/avatars/avatar_default_06_7E53C1.png", "description": "", "header_size": null, "restrict_posting": true, "restrict_commenting": false, "subscribers": 1, "is_default_icon": true, "link_flair_position": "", "display_name_prefixed": "u/HiveWriting_bot", "key_color": "", "name": "t5_zhwst", "is_default_banner": true, "url": "/user/HiveWriting_bot/", "banner_size": null, "user_is_moderator": true, "public_description": "", "link_flair_enabled": false, "subreddit_type": "user", "user_is_subscriber": false}, "is_sponsor": false, "gold_expiration": null, "has_gold_subscription": false, "num_friends": 0, "features": {"richtext_previews": true, "do_not_track": true, "chat_subreddit": true, "chat": true, "seq_randomize_sort": true, "sequence": true, "show_amp_link": true, "mweb_xpromo_revamp_v2": {"owner": "growth", "variant": "treatment_6", "experiment_id": 457}, "mweb_xpromo_interstitial_comments_ios": true, "chat_reddar_reports": true, "mweb_xpromo_modal_listing_click_daily_dismissible_ios": true, "chat_rollout": true, "mweb_xpromo_interstitial_comments_android": true, "chat_group_rollout": true, "mweb_link_tab": {"owner": "growth", "variant": "control_1", "experiment_id": 404}, "spez_modal": true, "mweb_xpromo_modal_listing_click_daily_dismissible_android": true, "community_awards": true, "default_srs_holdout": {"owner": "relevance", "variant": "popular", "experiment_id": 171}, "chat_user_settings": true, "dual_write_user_prefs": true}, "has_android_subscription": false, "verified": true, "new_modmail_exists": false, "pref_autoplay": true, "coins": 0, "has_paypal_subscription": false, "has_subscribed_to_premium": false, "id": "3kmf5q59", "has_stripe_subscription": false, "seen_premium_adblock_modal": false, "can_create_subreddit": true, "over_18": false, "is_gold": false, "is_mod": true, "suspension_expiration_utc": null, "has_verified_email": true, "is_suspended": false, "pref_video_autoplay": true, "in_chat": true, "in_redesign_beta": false, "icon_img": "https://www.redditstatic.com/avatars/avatar_default_06_7E53C1.png", "has_mod_mail": false, "pref_nightmode": false, "oauth_client_id": "PMQYCRTBZq6qHw", "hide_from_robots": false, "link_karma": 192, "force_password_reset": false, "inbox_count": 124, "pref_top_karma_subreddits": true, "has_mail": true, "pref_show_snoovatar": false, "name": "HiveWriting_bot", "pref_clickgadget": 5, "created": 1554873692.0, "gold_creddits": 0, "created_utc": 1554844892.0, "has_ios_subscription": false, "pref_show_twitter": false, "in_beta": false, "comment_karma": 7, "has_subscribed": true, "seen_subreddit_chat_ftux": false}`

	commentExampleJson = `{"json": {"errors": [], "data": {"things": [{"kind": "t1", "data": {"author_flair_background_color": null, "total_awards_received": 0, "approved_at_utc": null, "distinguished": null, "mod_reason_by": null, "banned_by": null, "author_flair_type": "text", "removal_reason": null, "link_id": "t3_bod8sf", "author_flair_template_id": null, "likes": true, "replies": "", "user_reports": [], "saved": false, "id": "enepbud", "banned_at_utc": null, "mod_reason_title": null, "gilded": 0, "archived": false, "no_follow": false, "author": "thecswbot", "rte_mode": "markdown", "can_mod_post": true, "created_utc": 1557802708.0, "send_replies": true, "parent_id": "t3_bod8sf", "score": 1, "author_fullname": "t2_knsbywx", "approved_by": null, "mod_note": null, "all_awardings": [], "subreddit_id": "t5_jke8s", "body": "My First Comment", "edited": false, "gildings": {}, "author_flair_css_class": null, "name": "t1_enepbud", "author_patreon_flair": false, "downs": 0, "author_flair_richtext": [], "is_submitter": true, "collapsed_reason": null, "body_html": "&lt;div class=\"md\"&gt;&lt;p&gt;My First Comment&lt;/p&gt;\n&lt;/div&gt;", "stickied": false, "can_gild": false, "removed": false, "approved": false, "author_flair_text_color": null, "score_hidden": false, "permalink": "/r/memeinvestor_test/comments/bod8sf/mypost/enepbud/", "num_reports": 0, "locked": false, "report_reasons": [], "created": 1557831508.0, "subreddit": "memeinvestor_test", "author_flair_text": null, "spam": false, "collapsed": false, "subreddit_name_prefixed": "r/memeinvestor_test", "controversiality": 0, "ignore_reports": false, "mod_reports": [], "subreddit_type": "public", "ups": 1}}]}}}`

	submissionExampleJson = ` {"json": {"errors": [], "data": {"url": "https://www.reddit.com/r/memeinvestor_test/comments/bod8sf/mypost/", "drafts_count": 0, "id": "bod8sf", "name": "t3_bod8sf"}}}`
)
