package mira

type Subreddit struct {
	Kind string
	Data SubredditData
}

type SubredditData struct {
	UserFlairBackgroundColor   string
	SubmitTextHtml             string
	RestrictPosting            bool
	UserIsBanned               bool
	FreeFormReports            bool
	WikiEnabled                bool
	UserIsMuted                bool
	UserCanFlairInSr           bool
	DisplayName                string
	HeaderImg                  string
	Title                      string
	IconSize                   []float64
	PrimaryColor               string
	ActiveUserCount            float64
	IconImg                    string
	AccountsActive             float64
	PublicTraffic              bool
	Subscribers                float64
	UserFlairRichtext          string
	VideostreamLinksCount      float64
	Name                       string
	Quarantine                 bool
	HideAds                    bool
	EmojisEnabled              bool
	AdvertiserCategory         string
	PublicDescription          string
	CommentScoreHideMins       float64
	UserHasFavorited           bool
	UserFlairTemplateId        string
	CommunityIcon              string
	BannerBackgroundImage      string
	OriginalContentTagEnabled  bool
	SubmitText                 string
	DescriptionHtml            string
	SpoilersEnabled            bool
	HeaderTitle                string
	HeaderSize                 string
	UserFlairPosition          string
	AllOriginalContent         bool
	HasMenuWidget              bool
	IsEnrolledInNewModmail     bool
	KeyColor                   string
	EventPostsEnabled bool
	CanAssignUserFlair         bool
	Created                    float64
	Wls                        string
	ShowMediaPreview           bool
	SubmissionType             string
	UserIsSubscriber           bool
	DisableContributorRequests bool
	AllowVideogifs             bool
	UserFlairType              string
	CollapseDeletedComments    bool
	EmojisCustomSize           string
	PublicDescriptionHtml      string
	AllowVideos                bool
	NotificationLevel          string
	CanAssignLinkFlair         bool
	AccountsActiveIsFuzzed     bool
	SubmitTextLabel            string
	LinkFlairPosition          string
	UserSrFlairEnabled         bool
	UserFlairEnabledInSr       bool
	AllowDiscovery             bool
	UserSrThemeEnabled         bool
	LinkFlairEnabled           bool
	SubredditType              string
	SuggestedCommentSort       string
	BannerImg                  string
	UserFlairText              string
	BannerBackgroundColor      string
	ShowMedia                  bool
	Id                         string
	UserIsModerator            bool
	Over18                     bool
	Description                string
	SubmitLinkLabel            string
	UserFlairTextColor         string
	RestrictCommenting         bool
	UserFlairCssClass          string
	AllowImages                bool
	Lang                       string
	WhitelistStatus            string
	Url                        string
	CreatedUtc                 float64
	BannerSize                 []float64
	MobileBannerImage          string
	UserIsContributor          bool
}
